Repository kosma/minmea, pull requests merged in 2022-06, with the labels that each got.

#63 Workflow
  .github/workflows/c-cpp.yml
  .travis.yml
  README.md
Labels: enhancement

#41 minmea: Allow lines with only CR ending
  minmea.c
  tests.c
Labels: bug, confirmed

#45 add minmea_getdate()
  minmea.c
  minmea.h
  tests.c
Labels: enhancement, requires thinking
